name: Move Assigned Issue to In Progress

on:
  issues:
    types:
      - assigned

jobs:
  move:
    name: Move
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to In Progress
        uses: immitsu/move-issue-on-assign@1f803bdb47cdc4e2ff4bf97aaa7ac74a0a9618d7 # v2.0.1
        with:
          token: ${{ secrets.PROJECTS_MOVE }}
          project: 1
          watch: 'Onboarding, Ready to Take'
          move-to: 'In Progress'
